version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: sisadb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: S45t3M4S.2022
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8080:8080"

volumes:
  pg_data: